DEEP LEARNING

In [1]:
!pip install torch torchvision torchaudio

Requirement already satisfied: torch in c:\lucky\lib\site-packages (2.8.0)
Requirement already satisfied: torchvision in c:\lucky\lib\site-packages (0.23.0)
Requirement already satisfied: torchaudio in c:\lucky\lib\site-packages (2.8.0)
Requirement already satisfied: filelock in c:\lucky\lib\site-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\lucky\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\lucky\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in c:\lucky\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\lucky\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in c:\lucky\lib\site-packages (from torch) (2025.3.2)
Requirement already satisfied: setuptools in c:\lucky\lib\site-packages (from torch) (72.1.0)
Requirement already satisfied: numpy in c:\lucky\lib\site-packages (from torchvision) (2.1.3)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\lucky\lib\site-packages (from torchvision) (11.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\lucky\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\lucky\lib\site-packages (from jinja2->torch) (3.0.2)

In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv("powerplant_data.csv")

In [3]:
df.head()

      AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [4]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [5]:
x=df.drop("PE",axis=1)
y=df["PE"]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
x_train

         AT      V       AP     RH
5487  25.24  63.47  1011.30  66.21
3522  26.09  70.40  1007.41  85.37
6916  26.63  73.68  1015.15  85.13
7544  32.06  71.85  1007.90  56.44
7600  28.70  71.64  1007.11  69.85
...     ...    ...      ...    ...
5734  26.25  61.02  1011.47  71.22
5191  29.17  64.79  1016.43  61.05
5390  18.00  43.70  1015.40  61.28
860   26.73  68.84  1010.75  66.83
7270   6.40  39.18  1024.60  86.83

[7654 rows x 4 columns]

In [8]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [9]:
x_test_scaled

array([[ 1.34499288,  0.23869298, -1.28658067, -1.10532538],
       [ 0.81095912,  1.36269098, -0.74140656,  0.26485915],
       [-0.2437241 , -0.73900436,  1.99970178, -0.19713193],
       ...,
       [-0.67068342, -1.15902881, -0.29951077, -0.10651852],
       [ 1.31420898,  1.33752097, -0.87346737, -0.44288647],
       [-0.2611237 , -0.27021304,  0.37433797,  1.10646548]])

In [10]:
import torch
import torch.nn as nn
import torch.optim as optim

In [11]:
nn

In [12]:
x_train_tensor=torch.tensor(x_train_scaled,dtype=torch.float32)

In [13]:
y_train_tensor=torch.tensor(y_train.values,dtype=torch.float32).view(-1,1)

In [14]:
x_test_tensor=torch.tensor(x_test_scaled,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test.values,dtype=torch.float32).view(-1,1)

In [15]:
from torch.utils.data import TensorDataset,DataLoader
train_dataset=TensorDataset(x_train_tensor,y_train_tensor)
test_dataset=TensorDataset(x_test_tensor,y_test_tensor)

In [16]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32)

In [17]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define the class
class ANN(nn.Module):
    def __init__(self, input_size):
        super(ANN, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_size, 6),
            nn.ReLU(),
            nn.Linear(6, 6),
            nn.ReLU(),
            nn.Linear(6, 1)
        )

    def forward(self, x):
        return self.model(x)

# Make sure x_train_tensor exists before this line
input_size = x_train_tensor.shape[1]

# Instantiate the model
model = ANN(input_size)

# Loss and optimizer
crietrion = nn.MSELoss()
optimizer = optim.Adam(model.parameters())

In [18]:
# Train the ANN
train_losses = []
val_losses = []

best_val_loss = float("inf")

epochs = 100

for epoch in range(epochs):
    model.train()
    running_loss = 0.0 # tot training loss for 1 epoch
    
    for xb, yb in train_loader:
        # xb = features of 1 batch
        # yb = labels of 1 batch
        optimizer.zero_grad()
        
        outputs = model(xb) # forward prop....predicted outputs for this batch
        loss = crietrion(outputs, yb) # compute loss
        loss.backward() # back prop.. compute gradients
        optimizer.step() # params update
        
        running_loss += loss.item() # loss is a tensor => py float

    epoch_train_loss = running_loss / len(train_loader)
    train_losses.append(epoch_train_loss)


    # Validation
    model.eval()
    running_val_loss = 0.0

    with torch.no_grad(): # no gradients compute
        for xb, yb in test_loader:
            outputs = model(xb)
            loss = crietrion(outputs, yb)
            running_val_loss += loss

    epoch_val_loss = running_val_loss / len(test_loader)
    val_losses.append(epoch_val_loss)

    print(f"epoch {epoch+1}/{epochs} ==> train loss = {epoch_train_loss} & val loss = {epoch_val_loss}")

epoch 1/100 ==> train loss = 204294.494921875 & val loss = 199380.703125
epoch 2/100 ==> train loss = 184030.633984375 & val loss = 161051.0625
epoch 3/100 ==> train loss = 127512.27630208334 & val loss = 92135.53125
epoch 4/100 ==> train loss = 63605.02900390625 & val loss = 41991.4921875
epoch 5/100 ==> train loss = 31210.00702718099 & val loss = 24047.630859375
epoch 6/100 ==> train loss = 20350.040934244793 & val loss = 17317.455078125
epoch 7/100 ==> train loss = 15199.019165039062 & val loss = 13050.2783203125
epoch 8/100 ==> train loss = 11297.896325683594 & val loss = 9430.4931640625
epoch 9/100 ==> train loss = 8059.570197550455 & val loss = 6600.84619140625
epoch 10/100 ==> train loss = 5545.743741861979 & val loss = 4418.4482421875
epoch 11/100 ==> train loss = 3592.9787389119465 & val loss = 2809.238037109375
epoch 12/100 ==> train loss = 2240.3229888916017 & val loss = 1741.3851318359375
epoch 13/100 ==> train loss = 1372.7863950093588 & val loss = 1074.4859619140625
epoch 14/100 ==> train loss = 843.6212491353352 & val loss = 663.5053100585938
epoch 15/100 ==> train loss = 522.2160298665365 & val loss = 414.41119384765625
epoch 16/100 ==> train loss = 327.47382221221926 & val loss = 265.7185363769531
epoch 17/100 ==> train loss = 213.19285116195678 & val loss = 175.20936584472656
epoch 18/100 ==> train loss = 142.1320742448171 & val loss = 118.42876434326172
epoch 19/100 ==> train loss = 98.70616374015808 & val loss = 83.85073852539062
epoch 20/100 ==> train loss = 69.92129185199738 & val loss = 60.48838806152344
epoch 21/100 ==> train loss = 52.21642367839813 & val loss = 46.64759063720703
epoch 22/100 ==> train loss = 40.848044482866925 & val loss = 36.49357604980469
epoch 23/100 ==> train loss = 33.73531483014425 & val loss = 30.934093475341797
epoch 24/100 ==> train loss = 29.22314025958379 & val loss = 26.82065773010254
epoch 25/100 ==> train loss = 26.273896012703577 & val loss = 23.762348175048828
epoch 26/100 ==> train loss = 24.391948556900026 & val loss = 22.24844741821289
epoch 27/100 ==> train loss = 23.04998944203059 & val loss = 20.97334098815918
epoch 28/100 ==> train loss = 22.222787563006083 & val loss = 20.55369758605957
epoch 29/100 ==> train loss = 21.727673530578613 & val loss = 19.735904693603516
epoch 30/100 ==> train loss = 21.40268976688385 & val loss = 19.863840103149414
epoch 31/100 ==> train loss = 21.283105727036794 & val loss = 19.22286033630371
epoch 32/100 ==> train loss = 21.08934174378713 & val loss = 19.360597610473633
epoch 33/100 ==> train loss = 21.00265306631724 & val loss = 19.00188636779785
epoch 34/100 ==> train loss = 20.964660704135895 & val loss = 19.068323135375977
epoch 35/100 ==> train loss = 20.85436752239863 & val loss = 19.85478973388672
epoch 36/100 ==> train loss = 20.823406982421876 & val loss = 19.086698532104492
epoch 37/100 ==> train loss = 20.69901495774587 & val loss = 18.95246696472168
epoch 38/100 ==> train loss = 20.823466678460438 & val loss = 18.985193252563477
epoch 39/100 ==> train loss = 20.74338119427363 & val loss = 19.22516632080078
epoch 40/100 ==> train loss = 20.91611028512319 & val loss = 19.0374813079834
epoch 41/100 ==> train loss = 20.74933992624283 & val loss = 18.75528335571289
epoch 42/100 ==> train loss = 20.73933466275533 & val loss = 18.852008819580078
epoch 43/100 ==> train loss = 20.81210022767385 & val loss = 19.201780319213867
epoch 44/100 ==> train loss = 20.72273781299591 & val loss = 18.73569107055664
epoch 45/100 ==> train loss = 20.62676223516464 & val loss = 18.658599853515625
epoch 46/100 ==> train loss = 20.73683657050133 & val loss = 19.09521484375
epoch 47/100 ==> train loss = 20.605693817138672 & val loss = 20.848419189453125
epoch 48/100 ==> train loss = 20.62125933965047 & val loss = 19.32320213317871
epoch 49/100 ==> train loss = 20.703323111931482 & val loss = 18.578956604003906
epoch 50/100 ==> train loss = 20.591776831944784 & val loss = 18.850818634033203
epoch 51/100 ==> train loss = 20.592023674647013 & val loss = 18.49077796936035
epoch 52/100 ==> train loss = 20.70753171443939 & val loss = 18.675798416137695
epoch 53/100 ==> train loss = 20.70704993009567 & val loss = 18.561872482299805
epoch 54/100 ==> train loss = 20.638310519854226 & val loss = 18.91803550720215
epoch 55/100 ==> train loss = 20.6157390276591 & val loss = 18.664615631103516
epoch 56/100 ==> train loss = 20.56240065495173 & val loss = 19.412647247314453
epoch 57/100 ==> train loss = 20.732143557071687 & val loss = 18.599668502807617
epoch 58/100 ==> train loss = 20.59862053593 & val loss = 18.724557876586914
epoch 59/100 ==> train loss = 20.62576171159744 & val loss = 18.501253128051758
epoch 60/100 ==> train loss = 20.58693952957789 & val loss = 18.724273681640625
epoch 61/100 ==> train loss = 20.580386412143707 & val loss = 19.00643539428711
epoch 62/100 ==> train loss = 20.727000017960865 & val loss = 18.76517677307129
epoch 63/100 ==> train loss = 20.64564150571823 & val loss = 18.525686264038086
epoch 64/100 ==> train loss = 20.611455579598744 & val loss = 18.766132354736328
epoch 65/100 ==> train loss = 20.619886664549508 & val loss = 18.56812286376953
epoch 66/100 ==> train loss = 20.579804968833923 & val loss = 19.407489776611328
epoch 67/100 ==> train loss = 20.536358699202538 & val loss = 18.43735122680664
epoch 68/100 ==> train loss = 20.5469491481781 & val loss = 19.82813835144043
epoch 69/100 ==> train loss = 20.548987690607706 & val loss = 19.328195571899414
epoch 70/100 ==> train loss = 20.68782634337743 & val loss = 18.558504104614258
epoch 71/100 ==> train loss = 20.560480690002443 & val loss = 18.601327896118164
epoch 72/100 ==> train loss = 20.608562183380126 & val loss = 18.67316436767578
epoch 73/100 ==> train loss = 20.493108383814494 & val loss = 19.280372619628906
epoch 74/100 ==> train loss = 20.560182543595634 & val loss = 19.010059356689453
epoch 75/100 ==> train loss = 20.655663488308587 & val loss = 18.496809005737305
epoch 76/100 ==> train loss = 20.57540022134781 & val loss = 18.930278778076172
epoch 77/100 ==> train loss = 20.456530467669168 & val loss = 18.68598747253418
epoch 78/100 ==> train loss = 20.489143772919974 & val loss = 19.809419631958008
epoch 79/100 ==> train loss = 20.56659713188807 & val loss = 19.93538475036621
epoch 80/100 ==> train loss = 20.54021335840225 & val loss = 19.605926513671875
epoch 81/100 ==> train loss = 20.5294021487236 & val loss = 18.78600311279297
epoch 82/100 ==> train loss = 20.422520933548608 & val loss = 19.297637939453125
epoch 83/100 ==> train loss = 20.740397614240646 & val loss = 18.87850570678711
epoch 84/100 ==> train loss = 20.536544835567476 & val loss = 18.75352668762207
epoch 85/100 ==> train loss = 20.599752269188564 & val loss = 18.561540603637695
epoch 86/100 ==> train loss = 20.586881693204244 & val loss = 18.697628021240234
epoch 87/100 ==> train loss = 20.60445326566696 & val loss = 18.722612380981445
epoch 88/100 ==> train loss = 20.527196276187897 & val loss = 20.58123779296875
epoch 89/100 ==> train loss = 20.477309785286586 & val loss = 18.50855255126953
epoch 90/100 ==> train loss = 20.61855054497719 & val loss = 18.605754852294922
epoch 91/100 ==> train loss = 20.512354028224944 & val loss = 18.83833885192871
epoch 92/100 ==> train loss = 20.58695202668508 & val loss = 18.42630958557129
epoch 93/100 ==> train loss = 20.401027325789133 & val loss = 19.056638717651367
epoch 94/100 ==> train loss = 20.464395654201507 & val loss = 18.948589324951172
epoch 95/100 ==> train loss = 20.451719057559966 & val loss = 18.47281837463379
epoch 96/100 ==> train loss = 20.473511719703673 & val loss = 19.03103256225586
epoch 97/100 ==> train loss = 20.50930696328481 & val loss = 18.645824432373047
epoch 98/100 ==> train loss = 20.441034360726675 & val loss = 18.660768508911133
epoch 99/100 ==> train loss = 20.56726929744085 & val loss = 19.286394119262695
epoch 100/100 ==> train loss = 20.565088347593942 & val loss = 18.541484832763672

In [19]:
if epoch_val_loss<best_val_loss:
    best_val_loss=epoch_val_loss
    torch.save(model.state_dict(),"good.pt")
    model.load_state_dict(torch.load("good.pt"))

In [20]:
model.eval()
with torch.no_grad():
    train_preds=model(x_train_tensor)
    test_preds=model(x_test_tensor)
    train_mse_loss=crietrion(train_preds,y_train_tensor)
    test_mse_loss=crietrion(test_preds,y_test_tensor)
    print("training mse:",train_mse_loss.item())
    print("testing mse:",test_mse_loss.item())
from sklearn.metrics import r2_score
print("r2 score:",r2_score(y_test,test_preds))

training mse: 20.194854736328125
testing mse: 18.54397201538086
r2 score: 0.9351935961436948

In [21]:
predicted_df=pd.DataFrame(test_preds.numpy(),columns=["predicted values"])
actual_df=pd.DataFrame(y_test.values,columns=["Actual values"])
pd.concat([predicted_df,actual_df],axis=1)

      predicted values  Actual values
0           434.962952         433.27
1           436.472321         438.16
2           461.357849         458.42
3           476.821991         480.82
4           434.433380         441.41
...                ...            ...
1909        451.647858         456.70
1910        431.100281         438.04
1911        468.283539         467.80
1912        430.415833         437.14
1913        456.818787         456.78

[1914 rows x 2 columns]

In [22]:
import pandas as pd
import numpy as np
df=pd.read_csv("DateFruit_Dataset.csv")

In [23]:
df

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.9080,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.1440,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.3940,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.2100,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.3540,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,255403,1925.3650,691.8453,477.1796,0.7241,570.2536,0.9785,261028,0.7269,1.4499,...,2.2423,2.3704,2.7202,-25296416768,-19168882688,-18473392128,49.0869,43.0422,42.4153,SOGAY
894,365924,2664.8230,855.4633,551.5447,0.7644,682.5752,0.9466,386566,0.6695,1.5510,...,3.4109,3.5805,3.9910,-31605219328,-21945366528,-19277905920,46.8086,39.1046,36.5502,SOGAY
895,254330,1926.7360,747.4943,435.6219,0.8126,569.0545,0.9925,256255,0.7240,1.7159,...,2.2759,2.5090,2.6951,-22242772992,-19594921984,-17592152064,44.1325,40.7986,40.9769,SOGAY
896,238955,1906.2679,716.6485,441.8297,0.7873,551.5859,0.9604,248795,0.6954,1.6220,...,2.6769,2.6874,2.7991,-26048595968,-21299822592,-19809978368,51.2267,45.7162,45.6260,SOGAY
897,343792,2289.2720,823.8438,534.7757,0.7607,661.6113,0.9781,351472,0.6941,1.5405,...,2.5138,3.0369,3.0865,-31983476736,-20482514944,-21219354624,47.3454,38.6966,39.6738,SOGAY

In [24]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [25]:
df.shape

(898, 35)

In [26]:
x=df.drop("Class",axis=1)
y=df["Class"]
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [27]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [29]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [30]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader,TensorDataset
import torch.optim as optimv

In [31]:
x_train_tensor=torch.tensor(x_train_scaled,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.long)
x_test_tensor=torch.tensor(x_test_scaled,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.long)

In [32]:
train_dataset=TensorDataset(x_train_tensor,y_train_tensor)
test_dataset=TensorDataset(x_test_tensor,y_test_tensor)

In [33]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32)

In [34]:
class ANN(nn.Module):
    def __init__(self):
        super(ANN,self).__init__()
        self.model=nn.Sequential(
        nn.Linear(x.shape[1],64),
        nn.ReLU(),
        nn.Linear(64,64),
        nn.ReLU(),
        nn.Linear(64,7),
        )
    def forward(self,x):
        return self.model(x)
model=ANN()
criteria=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters())

In [35]:
epochs=100
for epoch in range(epochs):
    model.train()
    running_loss=0.0
    for xb,yb in train_loader:
        optimizer.zero_grad()
        outputs=model(xb)
        loss=criteria(outputs,yb)
        loss.backward()
        optimizer.step()
        running_loss+=loss.item()
    train_loss=running_loss/len(train_loader)
    print(f"epoch={epoch+1}/{epochs};loss={train_loss}")

epoch=1/100;loss=1.6631891364636628
epoch=2/100;loss=1.120390930901403
epoch=3/100;loss=0.7432067018488179
epoch=4/100;loss=0.5346775819425997
epoch=5/100;loss=0.433590283860331
epoch=6/100;loss=0.3807770428450211
epoch=7/100;loss=0.3371939153774925
epoch=8/100;loss=0.30387758625590283
epoch=9/100;loss=0.2826885360738505
epoch=10/100;loss=0.2675750320372374
epoch=11/100;loss=0.23810335216314896
epoch=12/100;loss=0.23149245945007904
epoch=13/100;loss=0.2217030810273212
epoch=14/100;loss=0.20273739585409994
epoch=15/100;loss=0.19371194100898245
epoch=16/100;loss=0.1792951222995053
epoch=17/100;loss=0.18355905135040698
epoch=18/100;loss=0.16852495495391928
epoch=19/100;loss=0.1674412634709607
epoch=20/100;loss=0.15260840320716734
epoch=21/100;loss=0.15744928302972214
epoch=22/100;loss=0.1387444572604221
epoch=23/100;loss=0.14601245068985483
epoch=24/100;loss=0.1344725653205229
epoch=25/100;loss=0.1299099242719619
epoch=26/100;loss=0.12732319485234178
epoch=27/100;loss=0.12160007185910059
epoch=28/100;loss=0.1279953457415104
epoch=29/100;loss=0.11740970514390779
epoch=30/100;loss=0.11647420360342316
epoch=31/100;loss=0.11888275668025017
epoch=32/100;loss=0.11108905785595594
epoch=33/100;loss=0.10394122419149979
epoch=34/100;loss=0.10128557277114494
epoch=35/100;loss=0.09803025813206383
epoch=36/100;loss=0.09774514725026877
epoch=37/100;loss=0.10103921624629394
epoch=38/100;loss=0.0973928331842889
epoch=39/100;loss=0.10136227495968342
epoch=40/100;loss=0.09076127798660942
epoch=41/100;loss=0.08787023150564535
epoch=42/100;loss=0.08550779505268387
epoch=43/100;loss=0.08569632389623186
epoch=44/100;loss=0.08858413427420285
epoch=45/100;loss=0.08099286246072987
epoch=46/100;loss=0.08667660277822743
epoch=47/100;loss=0.08326647584529026
epoch=48/100;loss=0.07770643164606197
epoch=49/100;loss=0.07497184245806673
epoch=50/100;loss=0.07296024716418723
epoch=51/100;loss=0.07398626198182287
epoch=52/100;loss=0.07377818157977384
epoch=53/100;loss=0.07238658452811449
epoch=54/100;loss=0.06907368827935147
epoch=55/100;loss=0.06943514975516693
epoch=56/100;loss=0.0679188596246683
epoch=57/100;loss=0.06784789531451205
epoch=58/100;loss=0.06342547309949347
epoch=59/100;loss=0.0657565260063047
epoch=60/100;loss=0.06445194250377624
epoch=61/100;loss=0.0599149860765623
epoch=62/100;loss=0.06067693033053175
epoch=63/100;loss=0.06047284704349611
epoch=64/100;loss=0.05985562057922716
epoch=65/100;loss=0.05661241159490917
epoch=66/100;loss=0.0573873596832804
epoch=67/100;loss=0.05577579351223033
epoch=68/100;loss=0.05378920536326325
epoch=69/100;loss=0.05046568458656902
epoch=70/100;loss=0.05338751059025526
epoch=71/100;loss=0.047438210929217545
epoch=72/100;loss=0.047151390766805926
epoch=73/100;loss=0.05551307697011077
epoch=74/100;loss=0.050296636146452765
epoch=75/100;loss=0.04548530343353101
epoch=76/100;loss=0.04967068832205689
epoch=77/100;loss=0.044542517371313727
epoch=78/100;loss=0.04250191520575596
epoch=79/100;loss=0.0484662514746837
epoch=80/100;loss=0.05030601730813151
epoch=81/100;loss=0.043696770343281656
epoch=82/100;loss=0.0397642152586385
epoch=83/100;loss=0.03657073896054341
epoch=84/100;loss=0.039847202700279326
epoch=85/100;loss=0.03868663620770625
epoch=86/100;loss=0.03706468552674936
epoch=87/100;loss=0.03857569358028148
epoch=88/100;loss=0.03606032329085081
epoch=89/100;loss=0.042183549750758255
epoch=90/100;loss=0.03447679693446211
epoch=91/100;loss=0.03881294786444177
epoch=92/100;loss=0.0320722541326414
epoch=93/100;loss=0.03308584673694619
epoch=94/100;loss=0.033378205019170826
epoch=95/100;loss=0.02928263590792599
epoch=96/100;loss=0.029165405739584694
epoch=97/100;loss=0.028041018081990922
epoch=98/100;loss=0.03152373888651314
epoch=99/100;loss=0.028619342625303114
epoch=100/100;loss=0.025200365455416235

In [36]:
model.eval()

total = 0
correct = 0

with torch.no_grad():
    for xb, yb in test_loader:
        outputs = model(xb)
        _, predicted = torch.max(outputs, 1)

        correct += (predicted == yb).sum().item()
        total += yb.size(0)

print("total vals:", total)
print("correct values:", correct)
print("accuracy:", correct / total * 100)

total vals: 180
correct values: 171
accuracy: 95.0

In [37]:

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from torchvision.datasets import CIFAR10

In [38]:
from torch.utils.data import DataLoader
import torchvision.transforms as transforms

In [39]:
transform=transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))
])

In [40]:
trainset=CIFAR10(root="AIML.ipynb",train=True,download=True,transform=transform)

In [41]:
testset=CIFAR10(root="AIML.ipynb",train=False,download=True,transform=transform)

In [42]:
trainloader=DataLoader(trainset,batch_size=64,shuffle=True)

In [43]:
test_loader=DataLoader(testset,batch_size=64)

In [44]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN,self).__init__()
        self.conv_layers=nn.Sequential(
        nn.Conv2d(3,32,kernel_size=3,padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2,2),
        nn.Conv2d(32,64,kernel_size=3,padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2,2),
        nn.Conv2d(64,128,kernel_size=3,padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2,2),)
        self.fc_layers=nn.Sequential(nn.Linear(4*4*128, 256),
        nn.ReLU(),
        nn.Linear(256,10)
        )
    def forward(self,x):
        x=self.conv_layers(x)
        x=x.view(x.size(0),-1)
        x=self.fc_layers(x)
        return x

In [45]:
model=CNN()
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters())

In [46]:
epochs = 1

for epoch in range(epochs):
    epoch_training_loss = 0.0

    for images, labels in trainloader:
        optimizer.zero_grad()
        
        output = model.forward(images) # FP
        loss = criterion(output, labels) # loss fnx
        loss.backward() # BP
        optimizer.step() # update params

        epoch_training_loss += loss.item()

    print(f"epoch={epoch+1}/{epochs} & loss={epoch_training_loss/len(trainloader)}")

epoch=1/1 & loss=1.3679680120762048

In [47]:
correct_labels=0
total_labels=0
model.eval()
with torch.no_grad():
    for images,labels in test_loader:
        outputs=model.forward(images)
        _,predicted=torch.max(outputs,1)
        correct_labels+=(predicted==labels).sum().item()
        total_labels+=labels.size(0)
    print(f"accuracy={correct_labels/total_labels*100}")

accuracy=62.11

In [48]:
import pandas as pd
df=pd.read_csv("IMDB dataset.csv")

In [49]:
df.shape

(50000, 2)

In [50]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [51]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [52]:
df.drop_duplicates(inplace=True)

In [53]:
df.shape

(49582, 2)

In [54]:
df["review"]=df["review"].str.lower()

In [55]:
import re

In [56]:
def remove_urls(text):
    text=re.sub(r"http\S+","",text)
    return text
df["review"]=df["review"].apply(remove_urls)

In [57]:
def remove_puntuations(text):
    text=re.sub(r"[^A-Za-z0-9/s]","",text)
    return text
df["review"]=df["review"].apply(remove_puntuations)

In [58]:
def remove_html(text):
    text=re.sub(r"<.*?>","",text)
    return text
df["review"]=df["review"].apply(remove_html)

In [59]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')  # new requirement in recent NLTK versions
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sohai\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\sohai\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sohai\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [60]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [61]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [62]:
df.head()

                                              review sentiment
0  oneoftheotherreviewershasmentionedthatafterwat...  positive
1  awonderfullittleproductionbr/br/thefilmingtech...  positive
2  ithoughtthiswasawonderfulwaytospendtimeonatooh...  positive
3  basicallytheresafamilywherealittleboyjakethink...  negative
4  pettermatteisloveinthetimeofmoneyisavisuallyst...  positive

In [63]:
from nltk.stem import PorterStemmer
def stemming(text):
    ps=PorterStemmer()
    stemmed_words=[]
    tokens=word_tokenize(text)
    for token in tokens:
        stemmed_token=ps.stem(token)
        stemmed_words.append(stemmed_token)
        return "".join(stemmed_words)
df["review"]=df["review"].apply(stemming)

In [64]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["sentiment"]=le.fit_transform(df["sentiment"])
y=df["sentiment"]

In [65]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

In [66]:
df.head()

                                              review  sentiment
0  oneoftheotherreviewershasmentionedthatafterwat...          1
1  awonderfullittleproductionbr/br/thefilmingtech...          1
2  ithoughtthiswasawonderfulwaytospendtimeonatooh...          1
3  basicallytheresafamilywherealittleboyjakethink...          0
4  pettermatteisloveinthetimeofmoneyisavisuallyst...          1

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [68]:
tf=TfidfVectorizer(max_features=5000)
x=tf.fit_transform(df["review"])

In [69]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 38633 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 4395)	1.0
  (1, 4395)	1.0
  (2, 4395)	1.0
  (3, 4395)	0.38318966659021236
  (3, 2115)	0.923669680902476
  (4, 4395)	1.0
  (7, 4395)	1.0
  (8, 4395)	1.0
  (9, 4395)	1.0
  (10, 4395)	1.0
  (11, 4395)	1.0
  (12, 4395)	1.0
  (13, 4395)	1.0
  (17, 4395)	0.7907250346260184
  (17, 4472)	0.6121714789302767
  (18, 2880)	1.0
  (20, 4395)	1.0
  (21, 4395)	1.0
  (23, 4395)	0.3042192666360845
  (23, 115)	0.5499850415564055
  (23, 3712)	0.5499850415564055
  (23, 171)	0.5499850415564055
  (24, 4395)	1.0
  (25, 4395)	1.0
  (26, 4395)	0.7032254898933338
  :	:
  (49548, 239)	1.0
  (49555, 4395)	1.0
  (49556, 4395)	1.0
  (49557, 4395)	1.0
  (49559, 4395)	1.0
  (49560, 3109)	1.0
  (49561, 4395)	1.0
  (49562, 4395)	1.0
  (49563, 4395)	0.47737282246510043
  (49563, 23)	0.8787008526066785
  (49564, 4395)	1.0
  (49565, 4395)	1.0
  (49567, 4395)	1.0
  (49569, 4395)	1.0
  (49570, 4395)	1.0
  (49571, 4395)	1.0
  (49573, 4395)	1.0
  (49575, 4395)	1.0
  (49576, 4395)	0.8753975613297534
  (49576, 23)	0.4834036714981801
  (49577, 4395)	0.5866285989911698
  (49577, 23)	0.8098560902071782
  (49578, 4395)	1.0
  (49579, 4395)	1.0
  (49581, 4395)	1.0

In [70]:
x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 38633 stored elements and shape (49582, 5000)>

In [71]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [72]:
x_train.shape

(39665, 5000)

In [73]:
import torch
from torch.utils.data import TensorDataset,DataLoader

In [74]:
x_train=x_train.toarray()
x_test=x_test.toarray()

In [75]:
train_set=TensorDataset(
    torch.from_numpy(x_train).float(),
    torch.from_numpy(y_train.values).float()
)
test_set=TensorDataset(
    torch.from_numpy(x_test).float(),
    torch.from_numpy(y_test.values).float())

In [76]:
train_loader=DataLoader(train_set,shuffle=True,batch_size=64)
test_loader=DataLoader(test_set,shuffle=True,batch_size=64)

In [77]:
import torch.nn as nn
import torch.optim as optim

In [78]:
class RNN(nn.Module):
    def __init__(self,input_size,hidden_size=128,num_layers=1):
        super().__init__()
        self.hidden_size=hidden_size
        self.num_layers=num_layers
        self.rnn=nn.RNN(input_size,hidden_size,num_layers,batch_first=True)
        self.fc=nn.Linear(hidden_size,1)
    def forward(self,x):
        h0=torch.zeros(self.num_layers,x.size(0),self.hidden_size)
        out,_=self.rnn(x,h0)
        out=self.fc(out[:,-1,:])
        return out

In [79]:
input_size=x_train.shape[1]
model=RNN(input_size)
criterion=nn.BCELoss()
optimizer=optim.Adam(model.parameters())

In [80]:
epochs=10
for epoch in range(epochs):
    model.train()
    for xb,yb in train_loader:
        optimizer.zero_grad()
        xb=xb.unsqueeze(1)
        outputs=model(xb)
        outputs=torch.sigmoid(outputs.squeeze())
        loss=criterion(outputs,yb)
        loss.backward()
        optimizer.step()
    print(f"epoch ={epoch+1}/{epochs} and loss={loss.item()}")

epoch =1/10 and loss=0.6916674971580505
epoch =2/10 and loss=0.6998897194862366
epoch =3/10 and loss=0.6167159080505371
epoch =4/10 and loss=0.6953518986701965
epoch =5/10 and loss=0.6486122012138367
epoch =6/10 and loss=0.6406015753746033
epoch =7/10 and loss=0.6292611956596375
epoch =8/10 and loss=0.6095796823501587
epoch =9/10 and loss=0.6459051370620728
epoch =10/10 and loss=0.6515705585479736

In [81]:
model.eval()
with torch.no_grad():
    correct_vals=0
    tot_vals=0
    for xb,yb in test_loader:
        xb=xb.unsqueeze(1)
        outputs=model(xb)
        predicted=(torch.sigmoid(outputs.squeeze())>0.5).float()
        tot_vals+=yb.size(0)
        correct_vals+=(predicted==yb).sum().item()
    print(f"accuracy={correct_vals/tot_vals*100}")

accuracy=51.95119491781789

In [82]:
!pip install gymnasium

Requirement already satisfied: gymnasium in c:\lucky\lib\site-packages (1.2.3)
Requirement already satisfied: numpy>=1.21.0 in c:\lucky\lib\site-packages (from gymnasium) (2.1.3)
Requirement already satisfied: cloudpickle>=1.2.0 in c:\lucky\lib\site-packages (from gymnasium) (3.0.0)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\lucky\lib\site-packages (from gymnasium) (4.15.0)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\lucky\lib\site-packages (from gymnasium) (0.0.4)

In [83]:
!pip install "gymnasium[toy-text]"

Requirement already satisfied: gymnasium[toy-text] in c:\lucky\lib\site-packages (1.2.3)
Requirement already satisfied: numpy>=1.21.0 in c:\lucky\lib\site-packages (from gymnasium[toy-text]) (2.1.3)
Requirement already satisfied: cloudpickle>=1.2.0 in c:\lucky\lib\site-packages (from gymnasium[toy-text]) (3.0.0)
Requirement already satisfied: typing-extensions>=4.3.0 in c:\lucky\lib\site-packages (from gymnasium[toy-text]) (4.15.0)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\lucky\lib\site-packages (from gymnasium[toy-text]) (0.0.4)
Requirement already satisfied: pygame>=2.1.3 in c:\lucky\lib\site-packages (from gymnasium[toy-text]) (2.6.1)

In [ ]:
import gymnasium as gym
import numpy as np
import random

In [ ]:
env=gym.make("CliffWalking-v1")

In [ ]:
env

In [ ]:
print(env.observation_space.n)

In [ ]:
print(env.action_space.n)